export const INGREDIENTS = {
    "Alkanet Flower": [
        "Restore Intelligence",
        "Resist Poison",
        "Light",
        "Damage Fatigue",
    ],
    "Aloe Vera Leaves": [
        "Restore Fatigue",
        "Restore Health",
        "Damage Magicka",
        "Invisibility",
    ],
    "Ambrosia": ["Restore Health"],
    "Apple": ["Restore Fatigue", "Damage Luck", "Fortify Willpower", "Damage Health"],
    "Arrowroot": ["Restore Agility", "Damage Luck", "Fortify Strength", "Burden"],
    "Beef": ["Restore Fatigue", "Shield", "Fortify Agility", "Dispel"],
    "Bergamot Seeds": ["Resist Disease", "Dispel", "Damage Magicka", "Silence"],
    "Blackberry": [
        "Restore Fatigue",
        "Resist Shock",
        "Fortify Endurance",
        "Restore Magicka",
    ],
    "Bloodgrass": ["Chameleon", "Resist Paralysis", "Burden", "Fortify Health"],
    "Boar Meat": ["Restore Health", "Damage Speed", "Fortify Health", "Burden"],
    "Bog Beacon Asco Cap": [
        "Restore Magicka",
        "Shield",
        "Damage Personality",
        "Damage Endurance",
    ],
    "Bonemeal": ["Damage Fatigue", "Resist Fire", "Fortify Luck", "Night-Eye"],
    "Bread Loaf": [
        "Restore Fatigue",
        "Detect Life",
        "Damage Agility",
        "Damage Strength",
    ],
    "Cairn Bolete Cap": [
        "Restore Health",
        "Damage Intelligence",
        "Resist Paralysis",
        "Shock Damage",
    ],
    "Carrot": [
        "Restore Fatigue",
        "Night-Eye",
        "Fortify Intelligence",
        "Damage Endurance",
    ],
    "Cheese Wedge": ["Restore Fatigue", "Resist Fire", "Fire Shield", "Damage Agility"],
    "Cheese Wheel": [
        "Restore Fatigue",
        "Resist Paralysis",
        "Damage Luck",
        "Fortify Willpower",
    ],
    "Cinnabar Polypore Red Cap": [
        "Restore Agility",
        "Shield",
        "Damage Personality",
        "Damage Endurance",
    ],
    "Cinnabar Polypore Yellow Cap": [
        "Restore Endurance",
        "Fortify Endurance",
        "Damage Personality",
        "Reflect Spell",
    ],
    "Clannfear Claws": ["Cure Disease", "Resist Disease", "Paralyze", "Damage Health"],
    "Clouded Funnel Cap": [
        "Restore Intelligence",
        "Fortify Intelligence",
        "Damage Endurance",
        "Damage Magicka",
    ],
    "Columbine Root Pulp": [
        "Restore Personality",
        "Resist Frost",
        "Fortify Magicka",
        "Chameleon",
    ],
    "Corn": [
        "Restore Fatigue",
        "Restore Intelligence",
        "Damage Agility",
        "Shock Shield",
    ],
    "Crab Meat": ["Restore Endurance", "Resist Shock", "Damage Fatigue", "Fire Shield"],
    "Daedra Heart": ["Restore Health", "Shock Shield", "Damage Magicka", "Silence"],
    "Daedra Silk": ["Burden", "Night-Eye", "Chameleon", "Damage Endurance"],
    "Daedra Venin": ["Paralyze", "Restore Fatigue", "Damage Health", "Reflect Damage"],
    "Daedroth Teeth": ["Night-Eye", "Frost Shield", "Burden", "Light"],
    "Dragon.27s Tongue": [
        "Resist Fire",
        "Damage Health",
        "Restore Health",
        "Fire Shield",
    ],
    "Dreugh Wax": [
        "Damage Fatigue",
        "Resist Poison",
        "Water Breathing",
        "Damage Health",
    ],
    "Dryad Saddle Polypore Cap": [
        "Restore Luck",
        "Resist Frost",
        "Damage Speed",
        "Frost Damage",
    ],
    "Ectoplasm": ["Shock Damage", "Dispel", "Fortify Magicka", "Damage Health"],
    "Elf Cup Cap": [
        "Damage Willpower",
        "Cure Disease",
        "Fortify Strength",
        "Damage Intelligence",
    ],
    "Emetic Russula Cap": [
        "Restore Agility",
        "Shield",
        "Damage Personality",
        "Damage Endurance",
    ],
    "Fennel Seeds": [
        "Restore Fatigue",
        "Damage Intelligence",
        "Damage Magicka",
        "Paralyze",
    ],
    "Fire Salts": ["Fire Damage", "Resist Frost", "Restore Magicka", "Fire Shield"],
    "Flax Seeds": ["Restore Magicka", "Feather", "Shield", "Damage Health"],
    "Flour": [
        "Restore Fatigue",
        "Damage Personality",
        "Fortify Fatigue",
        "Reflect Damage",
    ],
    "Fly Amanita Cap": ["Restore Agility", "Burden", "Restore Health", "Shock Damage"],
    "Foxglove Nectar": [
        "Resist Poison",
        "Resist Paralysis",
        "Restore Luck",
        "Resist Disease",
    ],
    "Frost Salts": ["Frost Damage", "Resist Fire", "Silence", "Frost Shield"],
    "Garlic": ["Resist Disease", "Damage Agility", "Frost Shield", "Fortify Strength"],
    "Ginkgo Leaf": ["Restore Speed", "Fortify Magicka", "Damage Luck", "Shock Damage"],
    "Ginseng": ["Damage Luck", "Cure Poison", "Burden", "Fortify Magicka"],
    "Glow Dust": ["Restore Speed", "Light", "Reflect Spell", "Damage Health"],
    "Grapes": ["Restore Fatigue", "Water Walking", "Dispel", "Damage Health"],
    "Green Stain Cup Cap": [
        "Restore Fatigue",
        "Damage Speed",
        "Reflect Damage",
        "Damage Health",
    ],
    "Green Stain Shelf Cap": [
        "Restore Luck",
        "Fortify Luck",
        "Damage Fatigue",
        "Restore Health",
    ],
    "Ham": ["Restore Fatigue", "Restore Health", "Damage Magicka", "Damage Luck"],
    "Harrada": ["Damage Health", "Damage Magicka", "Silence", "Paralyze"],
    "Imp Gall": [
        "Fortify Personality",
        "Cure Paralysis",
        "Damage Health",
        "Fire Damage",
    ],
    "Ironwood Nut": [
        "Restore Intelligence",
        "Resist Fire",
        "Damage Fatigue",
        "Fortify Health",
    ],
    "Lady.27s Mantle Leaves": [
        "Restore Health",
        "Damage Endurance",
        "Night-Eye",
        "Feather",
    ],
    "Lady.27s Smock Leaves": [
        "Restore Intelligence",
        "Resist Fire",
        "Damage Fatigue",
        "Fortify Health",
    ],
    "Lavender Sprig": [
        "Restore Personality",
        "Fortify Willpower",
        "Restore Health",
        "Damage Luck",
    ],
    "Leek": [
        "Restore Fatigue",
        "Fortify Agility",
        "Damage Personality",
        "Damage Strength",
    ],
    "Lettuce": ["Restore Fatigue", "Restore Luck", "Fire Shield", "Damage Personality"],
    "Lichor": ["Restore Magicka"],
    "Mandrake Root": [
        "Cure Disease",
        "Resist Poison",
        "Damage Agility",
        "Fortify Willpower",
    ],
    "Milk Thistle Seeds": ["Light", "Frost Damage", "Cure Paralysis", "Paralyze"],
    "Minotaur Horn": [
        "Restore Willpower",
        "Burden",
        "Fortify Endurance",
        "Resist Paralysis",
    ],
    "Monkshood Root Pulp": [
        "Restore Strength",
        "Damage Intelligence",
        "Fortify Endurance",
        "Burden",
    ],
    "Morning Glory Root Pulp": [
        "Burden",
        "Damage Willpower",
        "Frost Shield",
        "Damage Magicka",
    ],
    "Mort Flesh": ["Damage Fatigue", "Damage Luck", "Fortify Health", "Silence"],
    "Motherwort Sprig": ["Resist Poison", "Damage Fatigue", "Silence", "Invisibility"],
    "Mugwort Seeds": ["Restore Health"],
    "Mutton": ["Fortify Health", "Damage Fatigue", "Dispel", "Damage Magicka"],
    "Nightshade": ["Damage Health", "Burden", "Damage Luck", "Fortify Magicka"],
    "Ogre.27s Teeth": [
        "Damage Intelligence",
        "Resist Paralysis",
        "Shock Damage",
        "Fortify Strength",
    ],
    "Onion": ["Restore Fatigue", "Water Breathing", "Detect Life", "Damage Health"],
    "Orange": ["Restore Fatigue", "Detect Life", "Burden", "Shield"],
    "Pear": ["Restore Fatigue", "Damage Speed", "Fortify Speed", "Damage Health"],
    "Peony Seeds": [
        "Restore Strength",
        "Damage Health",
        "Damage Speed",
        "Restore Fatigue",
    ],
    "Potato": ["Restore Fatigue", "Shield", "Burden", "Frost Shield"],
    "Primrose Leaves": [
        "Restore Willpower",
        "Restore Personality",
        "Fortify Luck",
        "Damage Strength",
    ],
    "Pumpkin": [
        "Restore Fatigue",
        "Damage Agility",
        "Damage Personality",
        "Detect Life",
    ],
    "Purgeblood Salts": [
        "Restore Magicka",
        "Damage Health",
        "Fortify Magicka",
        "Dispel",
    ],
    "Radish": ["Restore Fatigue", "Damage Endurance", "Chameleon", "Burden"],
    "Rat Meat": ["Damage Fatigue", "Detect Life", "Damage Magicka", "Silence"],
    "Redwort Flower": ["Resist Frost", "Cure Poison", "Damage Health", "Invisibility"],
    "Rice": ["Restore Fatigue", "Silence", "Shock Shield", "Damage Agility"],
    "Root Pulp": [
        "Cure Disease",
        "Damage Willpower",
        "Fortify Strength",
        "Damage Intelligence",
    ],
    "S.27jirra.27s Famous Potato Bread": [
        "Detect Life",
        "Restore Health",
        "Damage Agility",
        "Damage Strength",
    ],
    "Sacred Lotus Seeds": ["Resist Frost", "Damage Health", "Feather", "Dispel"],
    "Scales": ["Damage Willpower", "Water Breathing", "Damage Health", "Water Walking"],
    "Scamp Skin": ["Damage Magicka", "Resist Shock", "Reflect Damage", "Damage Health"],
    "Shepherd.27s Pie": ["Cure Disease", "Shield", "Fortify Agility", "Dispel"],
    "Somnalius Frond": [
        "Restore Speed",
        "Damage Endurance",
        "Fortify Health",
        "Feather",
    ],
    "Spiddal Stick": [
        "Damage Health",
        "Damage Magicka",
        "Fire Damage",
        "Restore Fatigue",
    ],
    "St. Jahn.27s Wort Nectar": [
        "Resist Shock",
        "Damage Health",
        "Cure Poison",
        "Chameleon",
    ],
    "Steel-Blue Entoloma Cap": [
        "Restore Magicka",
        "Fire Damage",
        "Resist Frost",
        "Burden",
    ],
    "Stinkhorn Cap": [
        "Damage Health",
        "Restore Magicka",
        "Water Walking",
        "Invisibility",
    ],
    "Strawberry": ["Restore Fatigue", "Cure Poison", "Damage Health", "Reflect Damage"],
    "Summer Bolete Cap": [
        "Restore Agility",
        "Shield",
        "Damage Personality",
        "Damage Endurance",
    ],
    "Sweetcake": ["Restore Fatigue", "Feather", "Restore Health", "Burden"],
    "Sweetroll": [
        "Restore Fatigue",
        "Resist Disease",
        "Damage Personality",
        "Fortify Health",
    ],
    "Taproot": ["Restore Luck", "Damage Endurance", "Resist Poison", "Shock Shield"],
    "Tiger Lily Nectar": [
        "Restore Endurance",
        "Damage Strength",
        "Water Walking",
        "Damage Willpower",
    ],
    "Tinder Polypore Cap": [
        "Restore Willpower",
        "Resist Disease",
        "Invisibility",
        "Damage Magicka",
    ],
    "Tobacco": ["Restore Fatigue", "Resist Paralysis", "Damage Magicka", "Dispel"],
    "Tomato": ["Restore Fatigue", "Detect Life", "Burden", "Shield"],
    "Troll Fat": [
        "Damage Agility",
        "Fortify Personality",
        "Damage Willpower",
        "Damage Health",
    ],
    "Vampire Dust": ["Silence", "Resist Disease", "Frost Damage", "Invisibility"],
    "Venison": ["Restore Health", "Feather", "Damage Health", "Chameleon"],
    "Viper.27s Bugloss Leaves": [
        "Resist Paralysis",
        "Night-Eye",
        "Burden",
        "Cure Paralysis",
    ],
    "Void Salts": ["Restore Magicka", "Damage Health", "Fortify Magicka", "Dispel"],
    "Water Hyacinth Nectar": [
        "Damage Luck",
        "Damage Fatigue",
        "Restore Magicka",
        "Fortify Magicka",
    ],
    "Watermelon": ["Restore Fatigue", "Light", "Burden", "Damage Health"],
    "Wheat Grain": [
        "Restore Fatigue",
        "Damage Magicka",
        "Fortify Health",
        "Damage Personality",
    ],
    "White Seed Pod": ["Restore Strength", "Water Breathing", "Silence", "Light"],
    "Wisp Stalk Caps": [
        "Damage Health",
        "Damage Willpower",
        "Damage Intelligence",
        "Fortify Speed",
    ],
    "Wormwood Leaves": [
        "Fortify Fatigue",
        "Invisibility",
        "Damage Health",
        "Damage Magicka",
    ],
}
export const EFFECTS = {
  "Burden": [
    "Orange",
    "Tomato",
    "Ginseng",
    "Nightshade",
    "Minotaur Horn",
    "Boar Meat",
    "Radish",
    "Bloodgrass",
    "Sweetcake",
    "Morning Glory Root Pulp",
    "Watermelon",
    "Monkshood Root Pulp",
    "Arrowroot",
    "Steel-Blue Entoloma Cap",
    "Fly Amanita Cap",
    "Viper.27s Bugloss Leaves",
    "Daedra Silk",
    "Potato",
    "Daedroth Teeth",
  ],
  "Chameleon": [
    "Bloodgrass",
    "Venison",
    "St. Jahn.27s Wort Nectar",
    "Daedra Silk",
    "Columbine Root Pulp",
    "Radish",
  ],
  "Cure Disease": [
    "Mandrake Root",
    "Root Pulp",
    "Elf Cup Cap",
    "Clannfear Claws",
    "Shepherd.27s Pie",
  ],
  "Cure Paralysis": [
    "Milk Thistle Seeds",
    "Imp Gall",
    "Viper.27s Bugloss Leaves",
  ],
  "Cure Poison": [
    "Redwort Flower",
    "Strawberry",
    "St. Jahn.27s Wort Nectar",
    "Ginseng",
  ],
  "Damage Agility": [
    "Cheese Wedge",
    "Garlic",
    "Bread Loaf",
    "Troll Fat",
    "Rice",
    "Mandrake Root",
    "S.27jirra.27s Famous Potato Bread",
    "Pumpkin",
    "Corn",
  ],
  "Damage Endurance": [
    "Emetic Russula Cap",
    "Carrot",
    "Summer Bolete Cap",
    "Cinnabar Polypore Red Cap",
    "Lady.27s Mantle Leaves",
    "Radish",
    "Bog Beacon Asco Cap",
    "Taproot",
    "Daedra Silk",
    "Clouded Funnel Cap",
    "Somnalius Frond",
  ],
  "Damage Fatigue": [
    "Lady.27s Smock Leaves",
    "Mort Flesh",
    "Water Hyacinth Nectar",
    "Crab Meat",
    "Green Stain Shelf Cap",
    "Alkanet Flower",
    "Motherwort Sprig",
    "Rat Meat",
    "Mutton",
    "Dreugh Wax",
    "Bonemeal",
    "Ironwood Nut",
  ],
  "Damage Health": [
    "Flax Seeds",
    "Purgeblood Salts",
    "Green Stain Cup Cap",
    "Harrada",
    "Nightshade",
    "Venison",
    "Dreugh Wax",
    "Apple",
    "Pear",
    "Spiddal Stick",
    "Wormwood Leaves",
    "Scamp Skin",
    "Scales",
    "Imp Gall",
    "Watermelon",
    "Strawberry",
    "Clannfear Claws",
    "Stinkhorn Cap",
    "Wisp Stalk Caps",
    "Ectoplasm",
    "Sacred Lotus Seeds",
    "Troll Fat",
    "Redwort Flower",
    "Daedra Venin",
    "Void Salts",
    "St. Jahn.27s Wort Nectar",
    "Grapes",
    "Onion",
    "Peony Seeds",
    "Dragon.27s Tongue",
    "Glow Dust",
  ],
  "Damage Intelligence": [
    "Cairn Bolete Cap",
    "Elf Cup Cap",
    "Root Pulp",
    "Ogre.27s Teeth",
    "Monkshood Root Pulp",
    "Fennel Seeds",
    "Wisp Stalk Caps",
  ],
  "Damage Luck": [
    "Ham",
    "Mort Flesh",
    "Water Hyacinth Nectar",
    "Ginseng",
    "Nightshade",
    "Arrowroot",
    "Cheese Wheel",
    "Lavender Sprig",
    "Apple",
    "Ginkgo Leaf",
  ],
  "Damage Magicka": [
    "Ham",
    "Wheat Grain",
    "Harrada",
    "Rat Meat",
    "Mutton",
    "Aloe Vera Leaves",
    "Spiddal Stick",
    "Tinder Polypore Cap",
    "Wormwood Leaves",
    "Morning Glory Root Pulp",
    "Scamp Skin",
    "Fennel Seeds",
    "Bergamot Seeds",
    "Tobacco",
    "Daedra Heart",
    "Clouded Funnel Cap",
  ],
  "Damage Personality": [
    "Emetic Russula Cap",
    "Wheat Grain",
    "Summer Bolete Cap",
    "Cinnabar Polypore Red Cap",
    "Flour",
    "Bog Beacon Asco Cap",
    "Leek",
    "Lettuce",
    "Sweetroll",
    "Pumpkin",
    "Cinnabar Polypore Yellow Cap",
  ],
  "Damage Speed": [
    "Dryad Saddle Polypore Cap",
    "Green Stain Cup Cap",
    "Pear",
    "Boar Meat",
    "Peony Seeds",
  ],
  "Damage Strength": [
    "S.27jirra.27s Famous Potato Bread",
    "Primrose Leaves",
    "Tiger Lily Nectar",
    "Bread Loaf",
    "Leek",
  ],
  "Damage Willpower": [
    "Morning Glory Root Pulp",
    "Root Pulp",
    "Elf Cup Cap",
    "Scales",
    "Tiger Lily Nectar",
    "Wisp Stalk Caps",
    "Troll Fat",
  ],
  "Detect Life": [
    "Rat Meat",
    "S.27jirra.27s Famous Potato Bread",
    "Pumpkin",
    "Orange",
    "Tomato",
    "Onion",
    "Bread Loaf",
  ],
  "Dispel": [
    "Purgeblood Salts",
    "Sacred Lotus Seeds",
    "Bergamot Seeds",
    "Ectoplasm",
    "Tobacco",
    "Mutton",
    "Void Salts",
    "Grapes",
    "Shepherd.27s Pie",
    "Beef",
  ],
  "Feather": [
    "Venison",
    "Flax Seeds",
    "Sweetcake",
    "Lady.27s Mantle Leaves",
    "Somnalius Frond",
    "Sacred Lotus Seeds",
  ],
  "Fire Damage": [
    "Spiddal Stick",
    "Steel-Blue Entoloma Cap",
    "Imp Gall",
    "Fire Salts",
  ],
  "Fire Shield": [
    "Cheese Wedge",
    "Dragon.27s Tongue",
    "Crab Meat",
    "Fire Salts",
    "Lettuce",
  ],
  "Fortify Agility": [
    "Shepherd.27s Pie",
    "Beef",
    "Leek",
  ],
  "Fortify Endurance": [
    "Blackberry",
    "Minotaur Horn",
    "Cinnabar Polypore Yellow Cap",
    "Monkshood Root Pulp",
  ],
  "Fortify Fatigue": [
    "Flour",
    "Wormwood Leaves",
  ],
  "Fortify Health": [
    "Lady.27s Smock Leaves",
    "Mort Flesh",
    "Wheat Grain",
    "Boar Meat",
    "Sweetroll",
    "Bloodgrass",
    "Mutton",
    "Ironwood Nut",
    "Somnalius Frond",
  ],
  "Fortify Intelligence": [
    "Clouded Funnel Cap",
    "Carrot",
  ],
  "Fortify Luck": [
    "Primrose Leaves",
    "Green Stain Shelf Cap",
    "Bonemeal",
  ],
  "Fortify Magicka": [
    "Water Hyacinth Nectar",
    "Ginseng",
    "Nightshade",
    "Purgeblood Salts",
    "Columbine Root Pulp",
    "Ectoplasm",
    "Void Salts",
    "Ginkgo Leaf",
  ],
  "Fortify Personality": [
    "Imp Gall",
    "Troll Fat",
  ],
  "Fortify Speed": [
    "Pear",
    "Wisp Stalk Caps",
  ],
  "Fortify Strength": [
    "Root Pulp",
    "Elf Cup Cap",
    "Garlic",
    "Ogre.27s Teeth",
    "Arrowroot",
  ],
  "Fortify Willpower": [
    "Mandrake Root",
    "Apple",
    "Cheese Wheel",
    "Lavender Sprig",
  ],
  "Frost Damage": [
    "Milk Thistle Seeds",
    "Vampire Dust",
    "Dryad Saddle Polypore Cap",
    "Frost Salts",
  ],
  "Frost Shield": [
    "Morning Glory Root Pulp",
    "Garlic",
    "Daedroth Teeth",
    "Potato",
    "Frost Salts",
  ],
  "Invisibility": [
    "Motherwort Sprig",
    "Redwort Flower",
    "Vampire Dust",
    "Aloe Vera Leaves",
    "Stinkhorn Cap",
    "Tinder Polypore Cap",
    "Wormwood Leaves",
  ],
  "Light": [
    "Watermelon",
    "White Seed Pod",
    "Milk Thistle Seeds",
    "Glow Dust",
    "Alkanet Flower",
    "Daedroth Teeth",
  ],
  "Night-Eye": [
    "Carrot",
    "Bonemeal",
    "Daedra Silk",
    "Lady.27s Mantle Leaves",
    "Viper.27s Bugloss Leaves",
    "Daedroth Teeth",
  ],
  "Paralyze": [
    "Daedra Venin",
    "Harrada",
    "Fennel Seeds",
    "Clannfear Claws",
    "Milk Thistle Seeds",
  ],
  "Reflect Damage": [
    "Scamp Skin",
    "Daedra Venin",
    "Green Stain Cup Cap",
    "Strawberry",
    "Flour",
  ],
  "Reflect Spell": [
    "Cinnabar Polypore Yellow Cap",
    "Glow Dust",
  ],
  "Resist Disease": [
    "Vampire Dust",
    "Garlic",
    "Clannfear Claws",
    "Foxglove Nectar",
    "Tinder Polypore Cap",
    "Sweetroll",
    "Bergamot Seeds",
  ],
  "Resist Fire": [
    "Cheese Wedge",
    "Lady.27s Smock Leaves",
    "Dragon.27s Tongue",
    "Bonemeal",
    "Ironwood Nut",
    "Frost Salts",
  ],
  "Resist Frost": [
    "Dryad Saddle Polypore Cap",
    "Redwort Flower",
    "Steel-Blue Entoloma Cap",
    "Columbine Root Pulp",
    "Fire Salts",
    "Sacred Lotus Seeds",
  ],
  "Resist Paralysis": [
    "Foxglove Nectar",
    "Cheese Wheel",
    "Minotaur Horn",
    "Viper.27s Bugloss Leaves",
    "Bloodgrass",
    "Cairn Bolete Cap",
    "Tobacco",
    "Ogre.27s Teeth",
  ],
  "Resist Poison": [
    "Mandrake Root",
    "Motherwort Sprig",
    "Alkanet Flower",
    "Dreugh Wax",
    "Foxglove Nectar",
    "Taproot",
  ],
  "Resist Shock": [
    "Blackberry",
    "Crab Meat",
    "Scamp Skin",
    "St. Jahn.27s Wort Nectar",
  ],
  "Restore Agility": [
    "Emetic Russula Cap",
    "Summer Bolete Cap",
    "Cinnabar Polypore Red Cap",
    "Arrowroot",
    "Fly Amanita Cap",
  ],
  "Restore Endurance": [
    "Crab Meat",
    "Cinnabar Polypore Yellow Cap",
    "Tiger Lily Nectar",
  ],
  "Restore Fatigue": [
    "Cheese Wedge",
    "Ham",
    "Orange",
    "Tomato",
    "Flour",
    "Rice",
    "Pear",
    "Corn",
    "Fennel Seeds",
    "Bread Loaf",
    "Strawberry",
    "Leek",
    "Sweetroll",
    "Daedra Venin",
    "Grapes",
    "Onion",
    "Peony Seeds",
    "Wheat Grain",
    "Green Stain Cup Cap",
    "Beef",
    "Radish",
    "Lettuce",
    "Pumpkin",
    "Sweetcake",
    "Aloe Vera Leaves",
    "Apple",
    "Spiddal Stick",
    "Blackberry",
    "Carrot",
    "Watermelon",
    "Cheese Wheel",
    "Tobacco",
    "Potato",
  ],
  "Restore Health": [
    "Ham",
    "Lady.27s Mantle Leaves",
    "Fly Amanita Cap",
    "Boar Meat",
    "Green Stain Shelf Cap",
    "Lavender Sprig",
    "Cairn Bolete Cap",
    "Daedra Heart",
    "Mugwort Seeds",
    "S.27jirra.27s Famous Potato Bread",
    "Dragon.27s Tongue",
    "Sweetcake",
    "Aloe Vera Leaves",
    "Venison",
    "Ambrosia",
  ],
  "Restore Intelligence": [
    "Lady.27s Smock Leaves",
    "Ironwood Nut",
    "Clouded Funnel Cap",
    "Alkanet Flower",
    "Corn",
  ],
  "Restore Luck": [
    "Dryad Saddle Polypore Cap",
    "Foxglove Nectar",
    "Green Stain Shelf Cap",
    "Taproot",
    "Lettuce",
  ],
  "Restore Magicka": [
    "Blackberry",
    "Flax Seeds",
    "Water Hyacinth Nectar",
    "Purgeblood Salts",
    "Stinkhorn Cap",
    "Steel-Blue Entoloma Cap",
    "Fire Salts",
    "Bog Beacon Asco Cap",
    "Void Salts",
    "Lichor",
  ],
  "Restore Personality": [
    "Lavender Sprig",
    "Primrose Leaves",
    "Columbine Root Pulp",
  ],
  "Restore Speed": [
    "Glow Dust",
    "Ginkgo Leaf",
    "Somnalius Frond",
  ],
  "Restore Strength": [
    "Peony Seeds",
    "White Seed Pod",
    "Monkshood Root Pulp",
  ],
  "Restore Willpower": [
    "Minotaur Horn",
    "Tinder Polypore Cap",
    "Primrose Leaves",
  ],
  "Shield": [
    "Emetic Russula Cap",
    "Flax Seeds",
    "Orange",
    "Tomato",
    "Summer Bolete Cap",
    "Cinnabar Polypore Red Cap",
    "Beef",
    "Bog Beacon Asco Cap",
    "Shepherd.27s Pie",
    "Potato",
  ],
  "Shock Damage": [
    "Cairn Bolete Cap",
    "Ogre.27s Teeth",
    "Fly Amanita Cap",
    "Ginkgo Leaf",
    "Ectoplasm",
  ],
  "Shock Shield": [
    "Taproot",
    "Daedra Heart",
    "Rice",
    "Corn",
  ],
  "Silence": [
    "Vampire Dust",
    "Mort Flesh",
    "Harrada",
    "Rice",
    "Frost Salts",
    "Bergamot Seeds",
    "Motherwort Sprig",
    "Daedra Heart",
    "Rat Meat",
    "White Seed Pod",
  ],
  "Water Breathing": [
    "White Seed Pod",
    "Scales",
    "Dreugh Wax",
    "Onion",
  ],
  "Water Walking": [
    "Stinkhorn Cap",
    "Scales",
    "Grapes",
    "Tiger Lily Nectar",
  ],
};
